apiVersion: v1
kind: Service
metadata:
  name: hello-world-backend
  labels:
    app: hello-world-backend
spec:
  ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: NodePort
  selector:
    app: hello-world-backend