apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-frontend
  labels:
    app: hello-world-frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0 
  selector:
    matchLabels:
      app: hello-world-frontend
  template:
    metadata:
      labels:
        app: hello-world-frontend
    spec:
      containers:
        - name: hello-world-frontend
          image: welmoki/hello-world-frontend
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 8080
          env:
          - name: PORT
            value: "8081"