apiVersion: v1
kind: Service
metadata:
  name: hello-world-frontend
  labels:
    app: hello-world-frontend
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: hello-world-frontend
  type: LoadBalancer
