name: Publish frontend docker image

on:
  push:
    branches: [main]
    paths: ['frontend/**']

defaults:
  run:
    working-directory: ./frontend  
  
env:
  REGISTRY: docker.io
  IMAGE_NAME: welmoki/hello-world-frontend
  SHA: ${{ github.event.pull_request.head.sha || github.event.after }}

jobs:
  push_to_registry:
    name: Push frontend docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.revision=${{ env.SHA }}
          tags: |
            type=edge,branch=$repo.default_branch
            type=semver,pattern=v{{version}}
            type=sha,prefix=,suffix=,format=short

      - name: Build and push frontend docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./frontend
          file: frontend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
