name: Golang

on:
  push:
    branches: [main]
    paths: ['golang/**']
  pull_request:
    branches: [main]
    paths: ['golang/**']

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Verify dependencies
      run: make backend-mod-verify

    - name: Build
      run: make backend-build

    - name: Run go vet
      run: make backend-vet

    - name: Run tests
      run: make backend-test